export const CATEGORIES_FETCHED = 'CATEGORIES_FETCHED'

export const POSTS_FETCHED = 'POSTS_FETCHED'
export const POSTS_VOTED = 'POSTS_VOTE'
export const POSTS_SORT_BY = 'POSTS_SORT_BY'
export const POSTS_POST_FETCHED = 'POSTS_POST_FETCHED'
export const POSTS_SHOW_UPDATE = 'POSTS_SHOW_UPDATE'
export const POSTS_SHOW_CREATE = 'POSTS_SHOW_CREATE'

export const COMMENTS_FETCHED = 'COMMENTS_FETCHED'
export const COMMENTS_VOTED = 'COMMENTS_VOTED'